//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetIdentity.Data.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int Id { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime PickupDate { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public int PickupLocationId { get; set; }
        public string ReturnLocationId { get; set; }
        public int CustomerId { get; set; }
        public int CarId { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Office Office { get; set; }
        public virtual User User { get; set; }
    }
}
